import { Brain, TrendingUp, Lightbulb } from "lucide-react";

function AIInsights() {
  return (
    <section className="activity-card">
      <h3>AI Insights</h3>
      <p>Business recommendations generated by AI</p>

      <div className="activity-list">

        <div className="activity-item">
          <div className="activity-icon">
            <TrendingUp size={18} />
          </div>

          <div>
            <h4>Sales increased by 18%</h4>
            <span>Compared to last month</span>
          </div>
        </div>

        <div className="activity-item">
          <div className="activity-icon">
            <Brain size={18} />
          </div>

          <div>
            <h4>High-value customers detected</h4>
            <span>Recommend personalized follow-up</span>
          </div>
        </div>

        <div className="activity-item">
          <div className="activity-icon">
            <Lightbulb size={18} />
          </div>

          <div>
            <h4>AI Recommendation</h4>
            <span>Focus marketing on CRM Platform customers</span>
          </div>
        </div>

      </div>
    </section>
  );
}

export default AIInsights;